In [1]:
import pandas as pd

# Adjust display format
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
df = pd.read_csv("salaries_by_college_major.csv")
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [3]:
# Check the number of rows and columns
df.shape

(51, 6)

In [4]:
# Check the labels of the columns
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

In [5]:
# Check for NaN values
df.isna

<bound method DataFrame.isna of                      Undergraduate Major  Starting Median Salary  \
0                             Accounting               46,000.00
1                  Aerospace Engineering               57,700.00
2                            Agriculture               42,600.00
3                           Anthropology               36,800.00
4                           Architecture               41,600.00
5                            Art History               35,800.00
6                                Biology               38,800.00
7                    Business Management               43,000.00
8                   Chemical Engineering               63,200.00
9                              Chemistry               42,600.00
10                     Civil Engineering               53,900.00
11                        Communications               38,100.00
12                  Computer Engineering               61,400.00
13                      Computer Science               55,900.00
14                          Construction               53,700.00
15                      Criminal Justice               35,000.00
16                                 Drama               35,900.00
17                             Economics               50,100.00
18                             Education               34,900.00
19                Electrical Engineering               60,900.00
20                               English               38,000.00
21                                  Film               37,900.00
22                               Finance               47,900.00
23                              Forestry               39,100.00
24                             Geography               41,200.00
25                               Geology               43,500.00
26                        Graphic Design               35,700.00
27            Health Care Administration               38,800.00
28                               History               39,200.00
29                 Hospitality & Tourism               37,800.00
30                Industrial Engineering               57,700.00
31           Information Technology (IT)               49,100.00
32                       Interior Design               36,100.00
33               International Relations               40,900.00
34                            Journalism               35,600.00
35  Management Information Systems (MIS)               49,200.00
36                             Marketing               40,800.00
37                                  Math               45,400.00
38                Mechanical Engineering               57,900.00
39                                 Music               35,900.00
40                               Nursing               54,200.00
41                             Nutrition               39,900.00
42                            Philosophy               39,900.00
43                   Physician Assistant               74,300.00
44                               Physics               50,300.00
45                     Political Science               40,800.00
46                            Psychology               35,900.00
47                              Religion               34,100.00
48                             Sociology               36,500.00
49                               Spanish               34,000.00
50                 Source: PayScale Inc.                     NaN

    Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                  77,100.00                          42,200.00
1                 101,000.00                          64,300.00
2                  71,900.00                          36,300.00
3                  61,500.00                          33,800.00
4                  76,800.00                          50,600.00
5                  64,900.00                          28,800.00
6                  64,800.00                          36,900.00
7                  72,100.00                          38,800.00
8                 107,000.00                          71,900.00
9                  79,900.00                          45,300.00
10                 90,500.00                          63,400.00
11                 70,000.00                          37,500.00
12                105,000.00                          66,100.00
13                 95,500.00                          56,000.00
14                 88,900.00                          56,300.00
15                 56,300.00                          32,200.00
16                 56,900.00                          36,700.00
17                 98,600.00                          50,600.00
18                 52,000.00                          29,300.00
19                103,000.00                          69,300.00
20                 64,700.00                          33,400.00
21                 68,500.00                          33,900.00
22                 88,300.00                          47,200.00
23                 62,600.00                          41,000.00
24                 65,500.00                          40,000.00
25                 79,500.00                          45,000.00
26                 59,800.00                          36,000.00
27                 60,600.00                          34,600.00
28                 71,000.00                          37,000.00
29                 57,500.00                          35,500.00
30                 94,700.00                          57,100.00
31                 74,800.00                          44,500.00
32                 53,200.00                          35,700.00
33                 80,900.00                          38,200.00
34                 66,700.00                          38,400.00
35                 82,300.00                          45,300.00
36                 79,600.00                          42,100.00
37                 92,400.00                          45,200.00
38                 93,600.00                          63,700.00
39                 55,000.00                          26,700.00
40                 67,000.00                          47,600.00
41                 55,300.00                          33,900.00
42                 81,200.00                          35,500.00
43                 91,700.00                          66,400.00
44                 97,300.00                          56,000.00
45                 78,200.00                          41,200.00
46                 60,400.00                          31,600.00
47                 52,000.00                          29,700.00
48                 58,200.00                          30,700.00
49                 53,100.00                          31,000.00
50                       NaN                                NaN

    Mid-Career 90th Percentile Salary     Group
0                          152,000.00  Business
1                          161,000.00      STEM
2                          150,000.00  Business
3                          138,000.00      HASS
4                          136,000.00  Business
5                          125,000.00      HASS
6                          135,000.00      STEM
7                          147,000.00  Business
8                          194,000.00      STEM
9                          148,000.00      STEM
10                         148,000.00      STEM
11                         143,000.00      HASS
12                         162,000.00      STEM
13                         154,000.00      STEM
14                         171,000.00  Business
15                         107,000.00      HASS
16                         153,000.00      HASS
17                         210,000.00  Business
18                         102,000.00      HASS
19                         168,000.00      STEM
20                         133,000.00      HASS
21                         136,000.00      HASS
22                         195,000.00  Business
23                         111,000.00  Business
24                         132,000.00      HASS
25                         156,000.00      STEM
26                         112,000.00      HASS
27                         101,000.00  Business
28                         149,000.00      HASS
29                         124,000.00  Business
30                         173,000.00      STEM
31                         129,000.00      STEM
32                         107,000.00      HASS
33                         157,000.00      HASS
34                         145,000.00      HASS
35                         146,000.00      STEM
36                         175,000.00  Business
37                         183,000.00      STEM
38                         163,000.00      STEM
39                         134,000.00      HASS
40                          98,300.00  Business
41                          99,200.00      HASS
42                         168,000.00      HASS
43                         124,000.00      STEM
44                         178,000.00      STEM
45                         168,000.00      HASS
46                         127,000.00      HASS
47                          96,400.00      HASS
48                         118,000.00      HASS
49                          96,400.00      HASS
50                                NaN       NaN  >

In [6]:
# Peek the end of the data frame
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [7]:
# Create a clean data frame without NULL values from the original data frame
clean_df = df.dropna()

In [8]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [9]:
# Find College Major with Highest Starting Salaries
starting_median_salaries = clean_df['Starting Median Salary']
highest_staring_median_salaries = starting_median_salaries.max()
highest_staring_median_salaries

np.float64(74300.0)

In [10]:
# Find the index of the college with max salary
college_idx = starting_median_salaries.idxmax()
college_idx

43

In [11]:
# Find the name of the major that corresponds to the max salary
major = clean_df['Undergraduate Major'].loc[43]
# major = clean_df['Undergraduate Major'][43]
major

'Physician Assistant'

In [12]:
# What college major has the highest mid-career salary?
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [13]:
# What college major has the lowest mid-career salary?
min_salary = clean_df['Mid-Career Median Salary'].min()
print(f"Min mid career salary: {min_salary}")
min_mid_salary_idx = clean_df['Mid-Career Median Salary'].idxmax()
print(f"Index for the min mid career salary: {min_mid_salary_idx}")
clean_df['Undergraduate Major'][8]

Min mid career salary: 52000.0
Index for the min mid career salary: 8

'Chemical Engineering'

In [14]:
# Calculate the difference between the earnings of the 10th and 90th percentile
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

In [15]:
# See which degrees have the smallest spread
lowest_sorted = clean_df.sort_values(by=['Spread'])
lowest_sorted.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
40,Nursing,"50,700.00","54,200.00","67,000.00","47,600.00","98,300.00",Business
43,Physician Assistant,"57,600.00","74,300.00","91,700.00","66,400.00","124,000.00",STEM
41,Nutrition,"65,300.00","39,900.00","55,300.00","33,900.00","99,200.00",HASS
49,Spanish,"65,400.00","34,000.00","53,100.00","31,000.00","96,400.00",HASS
27,Health Care Administration,"66,400.00","38,800.00","60,600.00","34,600.00","101,000.00",Business

In [16]:
# Find the top 5 degrees with the highest values in the 90th percentile
highest_sorted = clean_df.sort_values(by=['Spread'], ascending=False)
highest_sorted.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,"159,400.00","50,100.00","98,600.00","50,600.00","210,000.00",Business
22,Finance,"147,800.00","47,900.00","88,300.00","47,200.00","195,000.00",Business
37,Math,"137,800.00","45,400.00","92,400.00","45,200.00","183,000.00",STEM
36,Marketing,"132,900.00","40,800.00","79,600.00","42,100.00","175,000.00",Business
42,Philosophy,"132,500.00","39,900.00","81,200.00","35,500.00","168,000.00",HASS

In [17]:
# Which majors have the largest difference between high and low earners after graduation
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[["Undergraduate Major","Spread", "Group"]].head()

   Undergraduate Major     Spread     Group
17           Economics 159,400.00  Business
22             Finance 147,800.00  Business
37                Math 137,800.00      STEM
36           Marketing 132,900.00  Business
42          Philosophy 132,500.00      HASS

In [18]:
# Count how many majors we have in each category
clean_df.groupby("Group").count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [19]:
# Find the average spread of the majors
clean_df. groupby('Group')["Spread"].mean()

Group
Business   103,958.33
HASS        95,218.18
STEM       101,600.00
Name: Spread, dtype: float64